### ISSUE TITLE
Issue when checking out in case insensitive filesystem

### ISSUE THREAD

**Issue by fanzeyi** [learn-co-students/cs-application-crawling-lab-codeU#5]
There are two files with the same name different cases in the folder [javacs-lab11/src/resources/en.wikipedia.org/wiki](https://github.com/learn-co-students/cs-application-crawling-lab-codeU/tree/master/javacs-lab11/src/resources/en.wikipedia.org/wiki) (`Java_(Programming_Language)` and `Java_(programming_language)`). It causes problems when checking out in a case insensitive filesystem (HFS+ on Mac for example, setted case insensitive by default by Apple).

Please delete the redundant one.

![image](https://cloud.githubusercontent.com/assets/409951/15995672/c86b8b36-30d3-11e6-919f-f3f22970ec02.png)

**Comment by pletcher** [comment]
Fixed with https://github.com/learn-co-curriculum/cs-application-crawling-lab/commit/28937c7191a3e429b80224fdde4b84095867df9c
